### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by indiauppal** [leouieda/nene#6]
Issue when building on windows.

```
🏗   Building website...
📦 Loaded configuration from 'config.yml':
{
    'ignore': [
        'README.md',
        'LICENSE.md',
        'CONTRIBUTING.md',
        'environment.yml',
        'Makefile',
        'css/academicons/README.md',
        'config.yml'
    ],
    'output_dir': '_build',
    'templates_dir': '_templates',
    'copy': [],
    'site_name': 'Computer-Oriented Geoscience Lab',
    'site_description': 'Geophysical research powered by open-source software',
    'brand': 'images/compgeolab-banner.svg',
    'favicon': 'images/favicon.png',
    'url': 'https://www.compgeolab.org',
    'repository': 'compgeolab/website',
    'author': 'Leonardo Uieda',
    'twitter': 'leouieda',
    'github': 'compgeolab',
    'location': {
        'department': 'Department of Earth, Ocean and Ecological Sciences',
        'school': 'School of Environmental Sciences',
        'university': 'University of Liverpool',
        'country': 'UK'
    },
    'language': 'en',
    'keywords': 'science, geoscience, geophysics, software, open-source',
    'navigation': [
        {'name': 'Home', 'id': 'index'},
        {'name': 'Research', 'id': 'research/index'},
        {'name': 'Publications', 'id': 'publications/index'},
        {'name': 'Software', 'id': 'software/index'},
        {'name': 'Data', 'id': 'data/index'},
        {'name': 'Team', 'id': 'team/index'},
        {'name': 'News', 'id': 'news/index'},
        {'name': 'Contact', 'id': 'contact/index'}
    ]
}
📦 Captured information about the build environment:
{'today': datetime.datetime(2021, 9, 30, 11, 10, 15, 801434), 'nene_version': 'v0.2.0', 'commit': '090fba3'}
📂 Scanning source directory... Found:
   Markdown         = 16
   Jupyter notebook = 0
   YAML             = 5
   JSON             = 0
   Other            = 54
📖 Reading Markdown files:
   contact\index.md
   data\index.md
   index.md
   news\egu2020.md
   news\graduation2020.md
   news\index.md
   news\introduction.md
   news\liverpool-phd-2020.md
   news\liverpool-phd-2021.md
   news\ssi-fellowship.md
   news\transform2020.md
   news\transform2021.md
   publications\index.md
   research\index.md
   software\index.md
   team\index.md
📖 Reading Jupyter Notebook files as Markdown:
   There weren't any 😞
📖 Reading JSON data files:
   data\data.yml
   news\data.yml
   publications\papers.yml
Traceback (most recent call last):
  File "c:\users\india\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\india\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\india\anaconda3\Scripts\nene.exe\__main__.py", line 7, in <module>
  File "c:\users\india\anaconda3\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\india\anaconda3\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\india\anaconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\india\anaconda3\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\india\anaconda3\lib\site-packages\nene\cli.py", line 134, in main
    datum = load_data(path)
  File "c:\users\india\anaconda3\lib\site-packages\nene\core.py", line 314, in load_data
    data["content"] = parse_data_file(path)
  File "c:\users\india\anaconda3\lib\site-packages\nene\core.py", line 76, in parse_data_file
    data = loader[suffix](path.read_text())
  File "c:\users\india\anaconda3\lib\pathlib.py", line 1237, in read_text
    return f.read()
  File "c:\users\india\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 13203: character maps to <undefined>
```

**Comment by leouieda** [comment]
@indiauppal alright, problem solved and a new version on Nene is published. You can update by running `python -m pip install nene --upgrade`. Let me know if it works for you.

**Comment by indiauppal** [comment]
It's working now.

**Comment by leouieda** [comment]
🎉
